### ISSUE TITLE
I found this error : Undefined index: ccn

### ISSUE THREAD

**Issue by webmailcontatos** [sebastianbergmann/phploc#142] opened 2016-02-03 13:08 UTC
Version : phploc 3.0.0 by Sebastian Bergmann
Complete message : PHP Notice:  Undefined index: ccn in phar:///usr/local/bin/phploc/src/Analyser.php on line 507

Code who generate this error : 

<?php

namespace Collection\Util;

class Arr
{

    public static function flatten(array $array)
    {
        $return = [];
        function ($x) use (&$return)
        {
            $return[] = $x;
        }

    }

    public static function forget(array &$array, $keys)
    {
        foreach ($keys as $key) {

        }
    }

}

Thanks for atention

**Comment by Eternal-Infinity** [comment] 2016-02-04 05:51
Possible dublicate of #141?

**Comment by webmailcontatos** [comment] 2016-02-04 10:04
Is same problem but the code is different, maybe could be more a test

**Comment by sebastianbergmann** [comment] 2016-02-04 12:24
The problem seems to be related to the `use` in the closure declaration.

**Comment by KasperFranz** [comment] 2016-02-10 10:03
any ETA on the fix, as i'm not 100% sure what happens in the analyzer (it seems to be quiet complex)

**Comment by sebastianbergmann** [comment] 2016-02-10 11:19
It is too complex, I'm afraid, and should be rewritten from scratch.

**Comment by timhoeppner** [comment] 2016-02-10 13:50
@sebastianbergmann would there be anything wrong with just initializing the ccn index? See my diff below, works for me.

[https://github.com/timhoeppner/phploc/commit/e544f60f6663c222945ff3bd3c239351daa76ca6](https://github.com/timhoeppner/phploc/commit/e544f60f6663c222945ff3bd3c239351daa76ca6)

**Comment by sebastianbergmann** [comment] 2016-02-10 14:29
@timhoeppner That would just hide the problem.

**Comment by afoeder** [comment] 2016-03-18 12:47
We're suffering from this, too; and, well, I'm no mathematician, but it looks already wrong by looking at it: on line 507, the index ``ccn`` is increased without any check wether it's present; and looking above there is nothing which intrinsically will initialize it... So why not actually init it like @timhoeppner said?

Or _should_ the ccn index be there as of the algorithm and it's actually an error if it's not?

**Comment by webmailcontatos** [comment] 2016-03-18 13:21
Good question @afoeder . I have the same feeling

**Comment by sebastianbergmann** [comment] 2016-03-18 18:21
Sorry, but I have to repeat myself: that would just hide this problem and create another.

The problem here is that entire analyser should be rewritten. From scratch. Using either PHP-Parser (maybe with BetterReflection in front of it) or using PHP 7's internal AST. Trying to reason about PHP code just by looking at tokens is insane.

**Comment by sebastianbergmann** [comment] 2016-04-01 15:45
Duplicate of #141.

**Closed by sebastianbergmann** 2016-04-01 15:45 UTC
