### ISSUE TITLE
CSV Output Data

### ISSUE THREAD

**Issue by Nessworthy** [sebastianbergmann/phploc#131] opened 2015-11-19 12:19 UTC
Hi,

It seems that there's data omitted in the CSV output that is present in the STDOUT / Text statistics.
Here's a list of the comparison. `N/A` represents a heading / subheading.

Running version: 2.1.4

Text Label | CSV Label
-------------- | ---------------------
Directories | Directories
Files | Files
Lines of Code (LOC) | Lines of Code (LOC)
Size | `N/A`
....Comment Lines of Code (CLOC) | Comment Lines of Code (CLOC)
....Non-Comment Lines of Code (NCLOC) | Non-Comment Lines of Code (NCLOC)
....Logical Lines of Code (LLOC) | Logical Lines of Code (LLOC)
........Classes | Classes Length (LLOC)
............Average Class Length | -
................Minimum Class Length | -
................Maximum Class Length | -
............Average Method Length | -
................Minimum Method Length | -
................Maximum Method Length | -
........Functions | Functions Length (LLOC)
............Average Function Length | Average Function Length (LLOC)
........Not in classes or functions | LLOC outside functions or classes
Cyclomatic Complexity | `N/A`
....Average Complexity per LLOC | Cyclomatic Complexity / Lines of Code
....Average Complexity per Class | -
........Minimum Class Complexity | -
........Maximum Class Complexity | -
....Average Complexity per Method | Cyclomatic Complexity / Number of Methods
........Minimum Method Complexity | -
........Maximum Method Complexity | -
Dependencies | `N/A`
....Global Accesses | Global Accesses
........Global Constants | Global Constant Accesses
........Global Variables | Global Variable Accesses
........Super-Global Variables | Super-Global Variable Accesses
....Attribute Accesses | Attribute Accesses
........Non-Static | Non-Static Attribute Accesses
........Static | Static Attribute Accesses
....Method Calls | Method Calls
........Non-Static | Non-Static Method Calls
........Static | Static Method Calls
Structure | `N/A`
....Namespaces | Namespaces
....Interfaces | Interfaces
....Traits | Traits
....Classes | Classes
........Abstract Classes | Abstract Classes
........Concrete Classes | Concrete Classes
....Methods | Methods
........Scope | `N/A`
............Non-Static Methods | Non-Static Methods
............Static Methods | Static Methods
........Visibility | `N/A`
............Public Methods | Public Methods
............Non-Public Methods | Non-Public Methods
........Functions | Functions
............Named Functions | Named Functions
............Anonymous Functions | Anonymous Functions
........Constants | Constants
............Global Constants | Global Constants
............Class Constants | Class Constants
Tests | `N/A`
....Classes | Test Classes
....Methods | Test Methods

Would it be possible to include the blanks in the CSV report?

**Comment by johnkramlich** [comment] 2016-01-04 17:00
I'm in need of the same data in the CSV output. This pull request adds those missing pieces of data https://github.com/sebastianbergmann/phploc/pull/120 in case it's helpful to you before it gets mastered.

**Comment by Nessworthy** [comment] 2016-01-06 10:30
:+1: Thanks!

**Comment by sebastianbergmann** [comment] 2016-04-25 09:07
I had to close #120 because it no longer cleanly applied to `master. Feel free to send a fresh pull request. Sorry for not responding sooner.

**Comment by sebastianbergmann** [comment] 2016-04-25 09:07
Duplicate of #111.

**Closed by sebastianbergmann** 2016-04-25 09:07 UTC
