### ISSUE TITLE
Undefined index: lloc

### ISSUE THREAD

**Issue by leonardor** [sebastianbergmann/phploc#137] opened 2016-01-10 14:45 UTC
[phploc] phploc 2.1.5 by Sebastian Bergmann.
   [phploc]
   [phploc] PHP Notice:  Undefined index: lloc in phar:///phploc.phar/src/Analyser.php on line 312

**Comment by sebastianbergmann** [comment] 2016-01-11 08:26
Can you check whether the problem still exists in current `master`?

**Comment by sebastianbergmann** [comment] 2016-01-13 10:23
Duplicate of #125.

**Closed by sebastianbergmann** 2016-01-13 10:23 UTC
