### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by JeroenDeDauw** [sebastianbergmann/phploc#96] opened 2014-07-31 18:07 UTC
Got a fresh clone of `git@github.com:phpbb/phpbb.git`.

```
j@wd42:~/workspace/phpbb$ phploc phpBB/
phploc 2.0.6 by Sebastian Bergmann.

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/bin/phploc/src/Analyser.php on line 288
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phploc:0
PHP   2. Symfony\Component\Console\Application->run() /usr/local/bin/phploc:159
PHP   3. SebastianBergmann\PHPLOC\CLI\Application->doRun() phar:///usr/local/bin/phploc/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/phploc/src/CLI/Application.php:135
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/phploc/symfony/console/Symfony/Component/Console/Application.php:193
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/phploc/symfony/console/Symfony/Component/Console/Application.php:887
PHP   7. SebastianBergmann\PHPLOC\CLI\Command->execute() phar:///usr/local/bin/phploc/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. SebastianBergmann\PHPLOC\CLI\Command->executeSingle() phar:///usr/local/bin/phploc/src/CLI/Command.php:145
PHP   9. SebastianBergmann\PHPLOC\CLI\Command->count() phar:///usr/local/bin/phploc/src/CLI/Command.php:165
PHP  10. SebastianBergmann\PHPLOC\Analyser->countFiles() phar:///usr/local/bin/phploc/src/CLI/Command.php:266
PHP  11. SebastianBergmann\PHPLOC\Analyser->countFile() phar:///usr/local/bin/phploc/src/Analyser.php:175
PHP  12. token_get_all() phar:///usr/local/bin/phploc/src/Analyser.php:288
```

```
php -v
PHP 5.5.9-1ubuntu4.3 (cli) (built: Jul  7 2014 16:36:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
```

Also happened with phploc 2.0.5

**Comment by sebastianbergmann** [comment] 2015-03-01 13:07
Not a bug, closing.

**Closed by sebastianbergmann** 2015-03-01 13:07 UTC
